const Peliculas = []
class pelicula {
    constructor(ordenHistoria, ordenSalida, nombre, year, imagen, trailer, sinopsis) {
        this.ordenHistoria = ordenHistoria
        this.ordenSalida = ordenSalida
        this.nombre = nombre
        this.year = year
        this.imagen = imagen
        this.trailer = trailer
        this.sinopsis = sinopsis
    }
}
function pelisFaseUno() {
    Peliculas.push(new pelicula(3,0 , "Iron Man", 2008, "Iron_Man", "https://www.youtube.com/embed/EVFUfCUZbxk", "Tony Stark es un inventor de armamento brillante que es secuestrado en el extranjero. Sus captores son unos terroristas que le obligan a construir una máquina destructiva pero Tony se construirá una armadura para poder enfrentarse a ellos y escapar."))
    Peliculas.push(new pelicula(4,1 , "The Incredible Hulk", 2008, "The_incredible_Hulk", "https://www.youtube.com/embed/i2ueewdSiJg", "Bruce Banner recorre el mundo en busca de un antídoto para librarse de su alter ego. Además tendrá que hacer frente a Emil, un nuevo enemigo, lo que convertirá a Nueva York en el escenario de la última batalla entre las dos criaturas más poderosas."))
    Peliculas.push(new pelicula(5,2 , "Iron Man 2", 2010, "Iron_Man_2", "https://www.youtube.com/embed/IyPm8UlzOgU?start=20", "Con el mundo ahora consciente de que él es Iron Man, el millonario inventor Tony Stark debe forjar nuevas alianzas y enfrentarse a un nuevo y poderoso enemigo."))
    Peliculas.push(new pelicula(6,3 , "Thor", 2011, "Thor", "https://www.youtube.com/embed/n65Lkc-5zjQ", "Tras desatar una antigua guerra, el codicioso guerrero Thor es desterrado a la Tierra por su padre para que viva entre los hombres y descubra así el verdadero sentido de la humildad. Allí, sin sus poderes, Thor deberá enfrentarse a las fuerzas más oscuras que su mayor enemigo le enviará desde Asgard."))
    Peliculas.push(new pelicula(0,4 , "Captain America: The First Avenger", 2011, "Capitan_America_1", "https://www.youtube.com/embed/JnL7sjclx8k?start=7", "Tras tres meses de someterse a un programa de entrenamiento físico y táctico, Steve Rogers es encomendado su primera misión como Capitán América. Armado con un escudo indestructible, emprenderá la guerra contra el Mal como líder de los Vengadores."))
    Peliculas.push(new pelicula(7,5 , "The Avengers", 2012, "The_Avengers_1", "https://www.youtube.com/embed/4mwtDHovB3w", "El director de la Agencia SHIELD decide reclutar a un equipo para salvar al mundo de un desastre casi seguro cuando un enemigo inesperado surge como una gran amenaza para la seguridad mundial."))
}
pelisFaseUno()
function pelisFaseDos() {
    Peliculas.push(new pelicula(8,6 , "Iron Man 3", 2013, "Iron_Man_3", "https://www.youtube.com/embed/bKWvs_yCT6c", "El descarado y brillante Tony Stark, tras ver destruido todo su universo personal, debe encontrar y enfrentarse a un enemigo cuyo poder no conoce límites. Este viaje pondrá a prueba su entereza una y otra vez, y le obligará a confiar en su ingenio."))
    Peliculas.push(new pelicula(9,7 , "Thor: The Dark World", 2013, "Thor_TheDarkWorld", "https://www.youtube.com/embed/wyaK5HoeBJU", "Malekith, un enemigo más antiguo que el universo, regresa a la Tierra para cumplir su plan destructor. Thor debe enfrentarse a un rival al que ni siquiera Odín parece poder detener y, desesperado, libera a su hermano Loki para que lo ayude."))
    Peliculas.push(new pelicula(10,8 , "Captain America: The Winter Soldier", 2014, "Capitan_America_2", "https://www.youtube.com/embed/FmXjNGVpXUc", "Tras los devastadores acontecimientos vividos en Nueva York, el superhéroe vive tranquilamente en Washington D.C., intentando adaptarse al mundo moderno. Sin embargo, cuando un colega de el es amenazado, Rogers se ve envuelto en una trama de intrigas."))
    Peliculas.push(new pelicula(11,9 , "Guardians of the Galaxy", 2014, "Guardianes_de_la_galaxia", "https://www.youtube.com/embed/uvUMGJ66IfU", "El temerario aventurero Peter Quill, tras robar una misteriosa esfera codiciada por Ronan, un poderoso villano cuyas ambiciones amenazan a todo el universo, se convierte en la presa más codiciada por todos los cazarrecompensas de la galaxia."))
    Peliculas.push(new pelicula(13,10 , "Avengers: Age of Ultron", 2015, "Avengers_AgeOfUltron", "https://www.youtube.com/embed/hTCQgyrIt8g", "Tony Stark quiere lanzar un nuevo programa de paz, pero algo sale mal y acaba creando a Ultrón, un robot que quiere destruir a la humanidad. Los Vengadores deberán juntar sus fuerzas una vez más para luchar contra el robot. En su camino conocerán a dos nuevos misteriosos compañeros, Pietro y Wanda Maximoff, conocidos como Quicksilver y Bruja Escarlata."))
    Peliculas.push(new pelicula(14,11 , "Ant-Man", 2015, "Ant_Man", "https://www.youtube.com/embed/mBv4FSyg-P4", "El doctor Hank Pym anuncia que abandona S.H.I.E.L.D. tras descubrir que han tratado de apropiarse de la tecnología de su Ant-Man, que Pym considera altamente peligrosa. Varios años después, Scott Lang sale de prisión tras cumplir tres años de condena por robo."))
}
pelisFaseDos()
function pelisFaseTres() {
    Peliculas.push(new pelicula(15,12 , "Captain America: Civil War", 2016, "Capitan_America_CivilWar", "https://www.youtube.com/embed/IZAfpXFY3xw", "Mientras intentan detener a Rumlow en Lagos, Capitán América, Falcon, Viuda Negra y Bruja Escarlata se ven obligados a realizar una intervención para evitar el robo de una muestra letal en el Instituto de Enfermedades Infecciosas."))
    Peliculas.push(new pelicula(18,13 , "Doctor Strange", 2016, "Dr_Strange", "https://www.youtube.com/embed/ingOz2WNFjw", "La vida del famoso neurocirujano Dr. Stephen Strange cambia para siempre cuando un terrible accidente de coche le arrebata el uso de sus manos. Cuando la medicina tradicional le falla, busca la curación en un lugar misterioso llamado Kamar-Taj, que no solo es un centro de curación sino también el frente de una batalla contra fuerzas oscuras ocultas. Strange, armado con poderes mágicos recién adquiridos, debe elegir si regresar a su antigua vida o defender el mundo como su hechicero más poderoso."))
    Peliculas.push(new pelicula(12,14 , "Guardians of the Galaxy Vol. 2", 2017, "guardians-of-the-galaxy-vol2", "https://www.youtube.com/embed/1jd55ph3oqQ", "Una poderosa raza alienígena contrata a los Guardianes para que protejan sus valiosas baterías de energía, pero, cuando Rocket las roba, los alienígenas envían a sus tropas de combate a vengarse de los Guardianes. Mientras tratan de escapar con vida, intentan resolver el misterio de los verdaderos orígenes de Peter Quill."))
    Peliculas.push(new pelicula(19,15 , "Spider-Man: Homecoming", 2017, "Spider_Man_Homecoming", "https://www.youtube.com/embed/sfPWvYKKAJ4", "Peter Parker asume su nueva identidad como Spider-Man y regresa a vivir con su tía después de su aventura con los Vengadores. Al volver, mientras sigue bajo la tutela de Tony Stark, descubre que ha surgido un nuevo y despiadado enemigo que pretende destruir todo lo que ama: el Buitre."))
    Peliculas.push(new pelicula(21,16 , "Thor: Ragnarok", 2017, "Thor_Ragnarok", "https://www.youtube.com/embed/CM0rr8SPdlI", "Thor está preso en el otro extremo del universo. Necesita regresar a tiempo para evitar que la todopoderosa Hela destruya su mundo, pero para escapar de su confinamiento y evitar el apocalipsis tendrá que vencer antes al increíble Hulk en un torneo de gladiadores."))
    Peliculas.push(new pelicula(17,17 , "Black Panther", 2018, "Black_Panther", "https://www.youtube.com/embed/JcIye2DaZwI", "Hace millones de años, un meteorito de poderoso vibranium impactó en África. Cuando llegó la era del hombre, la mayoría de los habitantes de aquel territorio se unieron bajo el mando de un guerrero chamán que, gracias al vibranium, adquirió fuerza, velocidad e instinto sobrehumano, convirtiéndose en el primer Black Panther."))
    Peliculas.push(new pelicula(22,18 , "Avengers: Infinity War", 2018, "Avengers_Infinity_War", "https://www.youtube.com/embed/aAoKqx9wb1I", "Los superhéroes se alían para vencer al poderoso Thanos, el peor enemigo al que se han enfrentado. Si Thanos logra reunir las seis gemas del infinito: poder, tiempo, alma, realidad, mente y espacio, nadie podrá detenerlo."))
    Peliculas.push(new pelicula(20,19 , "Ant-Man and the Wasp", 2018, "Ant_Man_y_la_Avispa", "https://www.youtube.com/embed/1xdCWAagZfw", "Scott Lang vuelve a enfundarse el traje de Ant-Man para pelear codo a codo junto con la Avispa. La misión revela a los dos superhéroes un secreto terrible y los enfrenta a su enemigo más poderoso."))
    Peliculas.push(new pelicula(1,20 , "Captain Marvel", 2019, "captain_marvel", "https://www.youtube.com/embed/6XkN-MFNZpI", "La guerrera Vers no recuerda su pasado, el cual vuelve a ella en sueños. A pesar de sus problemas para controlar sus emociones y, con ellas, sus poderes, la Inteligencia Suprema le permite participar en una misión. Con la ayuda de Nick Fury tratará de descubrir los secretos de su pasado mientras aprovecha sus poderes para acabar con la guerra."))
    Peliculas.push(new pelicula(23,21 , "Avengers: Endgame", 2019, "avengers_endgame", "https://www.youtube.com/embed/znk2OICHbjY", "Después de los eventos devastadores de Avengers: Infinity War, el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar detenerlo y restaurar el orden en el universo de una vez por todas."))
    Peliculas.push(new pelicula(26,22 , "Spider-Man: Far From Home", 2019, "Spider_Man_Lejos_de_casa", "https://www.youtube.com/embed/PE3L0HHtOV0", "Peter Parker decide pasar unas merecidas vacaciones en Europa junto a MJ, Ned y el resto de sus amigos. Sin embargo, Peter debe volver a ponerse el traje de Spider-Man cuando Nick Fury le encomienda una nueva misión: frenar el ataque de unas criaturas que están causando el caos en el continente."))
}
pelisFaseTres()
function pelisFaseCuatro() {
    Peliculas.push(new pelicula(24,23 , "WandaVision", 2021, "WandaVision", "https://www.youtube.com/embed/UuhqbcMNrME", "Tres semanas después de los eventos de Avengers: Endgame (2019), Wanda Maximoff y Visión están viviendo una vida de ensueño en la pequeña ciudad de Westview, Nueva Jersey, tratando de ocultar sus verdaderas naturalezas. Pero a medida que pasan por nuevas décadas y cambian de escenarios televisivos, la pareja empieza a sospechar que las cosas no son lo que parecen."))
    Peliculas.push(new pelicula(25,24 , "The Falcon and the Winter Soldier", 2021, "Falcon_and_the_WinterSoldier", "https://www.youtube.com/embed/nxyckmizMUo", "Seis meses después de recibir el manto de Capitán América al final de Avengers: Endgame (2019), Sam Wilson se une a Bucky Barnes en una misión global para detener a un grupo antipatriotista, los Flag Smashers, que están mejorados con una recreación del suero del súper soldado y creen que el mundo era mejor durante el Blip."))
    Peliculas.push(new pelicula(27,25 , "Loki", 2021, "Loki", "https://www.youtube.com/embed/hXKnQpk1DZM", "Después de robar el Teseracto durante los eventos de Avengers: Endgame (2019), una versión alternativa de Loki es llevada ante la misteriosa organización llamada Autoridad de Variación Temporal, una organización burocrática que existe fuera del tiempo y el espacio, y monitorea la línea de tiempo. Le dan a Loki una opción: enfrentarse a ser borrado de la existencia debido a que es una «variante de tiempo» o ayudar a arreglar la línea de tiempo y detener una amenaza mayor. Loki termina atrapado en su propio thriller criminal, viajando en el tiempo."))
    Peliculas.push(new pelicula(16,26 , "Black Widow", 2021, "black_widow", "https://www.youtube.com/embed/Cy_znrsuXic", "Una peligrosa conspiración, relacionada con su pasado, persigue a Natasha Romanoff, también conocida como Viuda Negra. La agente tendrá que lidiar con las consecuencias de haber sido espía, así como con las relaciones rotas, para sobrevivir."))
    Peliculas.push(new pelicula(28,27 , "What If...?", 2021, "What_if", "https://www.youtube.com/embed/DexqOGh_tzQ", "Tras el establecimiento del multiverso en el final de la primera temporada de Loki, What If...? explora varias líneas de tiempo alternativas del multiverso en el que los momentos principales de las películas del Universo cinematográfico de Marvel (UCM) ocurren de manera diferente, según lo observado por el Vigilante."))
    Peliculas.push(new pelicula(31,28 , "Shang-Chi and the Legend of the Ten Rings", 2021, "Shang_Chi", "https://www.youtube.com/embed/Y_SS9K4N0K0", "El maestro de artes marciales Shang-Chi se enfrenta al pasado que creía haber dejado atrás cuando se ve envuelto en la red de la misteriosa organización de los Diez Anillos."))
    Peliculas.push(new pelicula(30,29 , "Eternals", 2021, "Eternals", "https://www.youtube.com/embed/MKWXuj3ZYf0", "Los Eternos son una raza de seres inmortales con poderes sobrehumanos que han vivido en secreto en la Tierra durante miles de años. Aunque nunca han intervenido en el destino de la población, ahora una amenaza se cierne sobre la humanidad."))
    Peliculas.push(new pelicula(32,30 , "Hawkeye", 2021, "hawkeye", "https://www.youtube.com/embed/eLb5trpCt9M", "Un año después de los eventos de Avengers: Endgame (2019), Clint Barton debe trabajar junto con la joven Kate Bishop para enfrentarse a los enemigos de su tiempo pasado como Ronin para poder volver con su familia a tiempo para Navidad."))
    Peliculas.push(new pelicula(29,31 , "Spider-Man: No Way Home", 2021, "Spider_Man_No_Way_Home", "https://www.youtube.com/embed/z70zo9gQUKA", "Tras descubrirse la identidad secreta de Peter Parker como Spider-Man, la vida del joven se vuelve una locura. Peter decide pedirle ayuda a Doctor Strange para recuperar su vida. Pero algo sale mal y provoca una fractura en el multiverso."))
    Peliculas.push(new pelicula(34,32 , "Moon Knight", 2022, "Moon_Night", "https://www.youtube.com/embed/0STDZqXCTxs", "Steven Grant (Oscar Isaac) un empleado de una tienda de regalos padece de afecciones en la memoria, quedándose en blanco o trayéndole recuerdos de otra vida. Hasta que descubre una verdad que le cambiara la vida por completo y le hará darse cuenta de la causa de sus afecciones de memoria."))
    Peliculas.push(new pelicula(33,33 , "Doctor Strange in the Multiverse of Madness", 2022, "Doctor_Strange_en_el_multiverso_de_la_locura", "https://www.youtube.com/embed/cFHjZfy50Kk", "El Dr. Stephen Strange abre un portal al multiverso al utilizar un hechizo prohibido. Ahora, su equipo debe enfrentarse a una amenaza que podría destruirlo todo."))
    Peliculas.push(new pelicula(35,34 , "Ms. Marvel", 2022, "ms_marvel", "https://www.youtube.com/embed/fH3gc-kr8Rc", "Kamala Khan, una fan de 16 años de los Vengadores, particularmente de Carol Danvers, lucha por encajar hasta que obtiene sus propios poderes."))
    Peliculas.push(new pelicula(36,35 , "Thor: Love and Thunder", 2022, "Thor_Love_and_Thunder", "https://www.youtube.com/embed/pR6pOzwP2Vo", "Thor está buscando la paz interior, pero la irrupción de Gorr, el asesino de dioses, le obliga a volver al combate. Thor recluta a la Reina Valkiria, Korg y su exnovia, Jane Foster, para que lo ayuden a evitar la extinción de los dioses."))
}
pelisFaseCuatro()