const btnDetalleIron_Man = document.querySelector("#Iron_Man")
const btnDetalleThe_incredible_Hulk = document.querySelector("#The_incredible_Hulk")
const btnDetalleIron_Man_2 = document.querySelector("#Iron_Man_2")
const btnDetalleThor = document.querySelector("#Thor")
const btnDetalleCapitan_America_1 = document.querySelector("#Capitan_America_1")
const btnDetalleThe_Avengers_1 = document.querySelector("#The_Avengers_1")
const btnDetalleIron_Man_3 = document.querySelector("#Iron_Man_3")
const btnDetalleThor_TheDarkWorld = document.querySelector("#Thor_TheDarkWorld")
const btnDetalleCapitan_America_2 = document.querySelector("#Capitan_America_2")
const btnDetalleGuardianes_de_la_galaxia = document.querySelector("#Guardianes_de_la_galaxia")
const btnDetalleAvengers_AgeOfUltron = document.querySelector("#Avengers_AgeOfUltron")
const btnDetalleAnt_Man = document.querySelector("#Ant_Man")
const btnDetalleCapitan_America_CivilWar = document.querySelector("#Capitan_America_CivilWar")
const btnDetalleDr_Strange = document.querySelector("#Dr_Strange")
const btnDetalleguardians2 = document.querySelector("#guardians-of-the-galaxy-vol2")
const btnDetalleSpider_Man_Homecoming = document.querySelector("#Spider_Man_Homecoming")
const btnDetalleThor_Ragnarok = document.querySelector("#Thor_Ragnarok")
const btnDetalleBlack_Panther = document.querySelector("#Black_Panther")
const btnDetalleAvengers_Infinity_War = document.querySelector("#Avengers_Infinity_War")
const btnDetalleAnt_Man_y_la_Avispa = document.querySelector("#Ant_Man_y_la_Avispa")
const btnDetallecaptain_marvel = document.querySelector("#captain_marvel")
const btnDetalleavengers_endgame = document.querySelector("#avengers_endgame")
const btnDetalleSpider_Man_Lejos_de_casa = document.querySelector("#Spider_Man_Lejos_de_casa")
const btnDetalleWandaVision = document.querySelector("#WandaVision")
const btnDetalleFalcon_and_the_WinterSoldier = document.querySelector("#Falcon_and_the_WinterSoldier")
const btnDetalleLoki = document.querySelector("#Loki")
const btnDetalleblack_widow = document.querySelector("#black_widow")
const btnDetalleWhat_if = document.querySelector("#What_if")
const btnDetalleShang_Chi = document.querySelector("#Shang_Chi")
const btnDetalleEternals = document.querySelector("#Eternals")
const btnDetallehawkeye = document.querySelector("#hawkeye")
const btnDetalleSpider_Man_No_Way_Home = document.querySelector("#Spider_Man_No_Way_Home")
const btnDetalleMoon_Night = document.querySelector("#Moon_Night")
const btnDetalleDoctor_Strange_en_el_multiverso_de_la_locura = document.querySelector("#Doctor_Strange_en_el_multiverso_de_la_locura")
const btnDetallems_marvel = document.querySelector("#ms_marvel")
const btnDetalleThor_Love_and_Thunder = document.querySelector("#Thor_Love_and_Thunder")
//btnDetalleIron_Man.addEventListener("click", recorrerBtn(Iron_Man))
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
// btnDetalle.addEventListener("click", recorrerBtn())
